version: '3.8'

services:
  backend:
    image: 9860459806/gharbhadabackend:latest
    command: bash -c "npx prisma migrate dev && npx prisma generate && node index.js"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase
    depends_on:
      - postgres
    networks:
      - mynetwork
  frontend:
    build: ./client
    ports:
      - "80:80"
  
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
